print("KRISHAND INDONESIA")
print("Jakarta Selatan - Indonesia")
print("------------------------------------------------------------------------------------------")
print("                                 I N V O I C E                                            ")
print("Kepada Yth.                                                    No.       :FT./003/01/2008 ")
print("No     : FT/003/01/2008")
print("Tanggal: 30/01/2008")
print("Mata Uang: IDR")
print("------------------------------")
print("Nama Barang | Qty | Harga")
print("Kaos Polo   | 25  | 40000")
print("T-Shirt     | 5   | 20000")
print("------------------------------")
print("Total : 1.270.000")
print("PPN   : 127.000")
print("Grand Total : 1.397.000")
print("==============================")